#include "attention_decode.h"
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <vector>

namespace {
using qw38::cuda::AttentionCache;
using qw38::cuda::AttentionConfig;
struct B { float *q{},*k{},*v{},*g{},*qs{},*ks{},*nq{},*nk{},*score{},*out{}; __nv_bfloat16 *ck{},*cv{},*tk{},*tv{}; };
void release(B& b){cudaFree(b.tv);cudaFree(b.tk);cudaFree(b.cv);cudaFree(b.ck);cudaFree(b.out);cudaFree(b.score);cudaFree(b.nk);cudaFree(b.nq);cudaFree(b.ks);cudaFree(b.qs);cudaFree(b.g);cudaFree(b.v);cudaFree(b.k);cudaFree(b.q);}
bool allocate(B& b,const AttentionConfig& c,size_t rows,size_t start){size_t q=qw38::cuda::attention_query_values(c),r=qw38::cuda::attention_kv_row_values(c),cv=qw38::cuda::attention_cache_values(c),s=qw38::cuda::attention_chunk_score_values(c,start,rows);
#define A(x,n) if(cudaMalloc(reinterpret_cast<void**>(&b.x),(n)*sizeof(*b.x))!=cudaSuccess)return false
A(q,rows*q);A(k,rows*r);A(v,rows*r);A(g,rows*q);A(qs,c.head_width);A(ks,c.head_width);A(nq,q);A(nk,r);A(score,s);A(out,rows*q);A(ck,cv);A(cv,cv);A(tk,rows*r);A(tv,rows*r);
#undef A
return true;}
void seed(B& b,const AttentionConfig& c,size_t rows,size_t start){size_t q=qw38::cuda::attention_query_values(c),r=qw38::cuda::attention_kv_row_values(c),cv=qw38::cuda::attention_cache_values(c);std::vector<float> hq(rows*q),hk(rows*r),hv(rows*r),hg(rows*q),s(c.head_width,1.f);for(size_t i=0;i<hq.size();++i){hq[i]=sinf(float(i)*.001f);hg[i]=cosf(float(i)*.002f);}for(size_t i=0;i<hk.size();++i){hk[i]=cosf(float(i)*.003f);hv[i]=sinf(float(i)*.004f);}std::vector<__nv_bfloat16> z(cv);for(size_t i=0;i<cv;++i)z[i]=__float2bfloat16_rn(float(int(i%31)-15)*.015625f);cudaMemcpy(b.q,hq.data(),hq.size()*sizeof(float),cudaMemcpyHostToDevice);cudaMemcpy(b.k,hk.data(),hk.size()*sizeof(float),cudaMemcpyHostToDevice);cudaMemcpy(b.v,hv.data(),hv.size()*sizeof(float),cudaMemcpyHostToDevice);cudaMemcpy(b.g,hg.data(),hg.size()*sizeof(float),cudaMemcpyHostToDevice);cudaMemcpy(b.qs,s.data(),s.size()*sizeof(float),cudaMemcpyHostToDevice);cudaMemcpy(b.ks,s.data(),s.size()*sizeof(float),cudaMemcpyHostToDevice);cudaMemcpy(b.ck,z.data(),z.size()*sizeof(__nv_bfloat16),cudaMemcpyHostToDevice);cudaMemset(b.score,0xA5,qw38::cuda::attention_chunk_score_values(c,start,rows)*sizeof(float));}
cudaError_t invoke(const AttentionConfig& c,size_t start,size_t rows,B& b,bool ref,cudaStream_t stream){AttentionCache committed{b.ck,b.cv},candidate{b.tk,b.tv};return ref?qw38::cuda::launch_attention_prepare_chunk_reference(c,start,rows,b.q,b.k,b.v,b.qs,b.ks,b.g,committed,candidate,b.nq,b.nk,b.score,b.out,stream):qw38::cuda::launch_attention_prepare_chunk(c,start,rows,b.q,b.k,b.v,b.qs,b.ks,b.g,committed,candidate,b.nq,b.nk,b.score,b.out,stream);}
int capture(const AttentionConfig& c,size_t start,size_t rows,B& b,bool ref){cudaStream_t s{};cudaGraph_t g{};cudaGraphExec_t e{};if(cudaStreamCreateWithFlags(&s,cudaStreamNonBlocking)!=cudaSuccess)return -1;if(cudaStreamBeginCapture(s,cudaStreamCaptureModeGlobal)!=cudaSuccess)return -1;cudaError_t x=invoke(c,start,rows,b,ref,s);if(x==cudaSuccess)x=cudaStreamEndCapture(s,&g);if(x!=cudaSuccess){cudaStreamDestroy(s);return -1;}size_t n=0;std::vector<cudaGraphNode_t> nodes;if(x==cudaSuccess)x=cudaGraphGetNodes(g,nullptr,&n);if(x==cudaSuccess){nodes.resize(n);x=cudaGraphGetNodes(g,nodes.data(),&n);}if(x==cudaSuccess)x=cudaGraphInstantiate(&e,g,nullptr,nullptr,0);if(x==cudaSuccess)x=cudaGraphLaunch(e,s);if(x==cudaSuccess)x=cudaStreamSynchronize(s);int k=0;for(auto node:nodes){cudaGraphNodeType t{};if(cudaGraphNodeGetType(node,&t)==cudaSuccess&&t==cudaGraphNodeTypeKernel)++k;}cudaGraphExecDestroy(e);cudaGraphDestroy(g);cudaStreamDestroy(s);return x==cudaSuccess?k:-1;}
float maxabs(const std::vector<float>&a,const std::vector<float>&b){float m=0;for(size_t i=0;i<a.size();++i)m=fmaxf(m,fabsf(a[i]-b[i]));return m;}float rms(const std::vector<float>&a,const std::vector<float>&b){double s=0;for(size_t i=0;i<a.size();++i){double d=a[i]-b[i];s+=d*d;}return sqrtf(float(s/a.size()));}float cosine(const std::vector<float>&a,const std::vector<float>&b){double ab=0,aa=0,bb=0;for(size_t i=0;i<a.size();++i){ab+=a[i]*b[i];aa+=a[i]*a[i];bb+=b[i]*b[i];}return float(ab/sqrt(aa*bb));}
}
int main(){
  AttentionConfig c{24,4,256,64,131072}; size_t rows=9,start=5,q=qw38::cuda::attention_query_values(c),s=qw38::cuda::attention_chunk_score_values(c,start,rows); B t{},r{};
  if(!allocate(t,c,rows,start)||!allocate(r,c,rows,start)) return 2; seed(t,c,rows,start); seed(r,c,rows,start);
  std::vector<float>a(rows*q),b(a.size()),before(s),after(s); cudaMemcpy(before.data(),t.score,s*sizeof(float),cudaMemcpyDeviceToHost);
  if(invoke(c,start,rows,t,false,nullptr)!=cudaSuccess||cudaDeviceSynchronize()!=cudaSuccess)return 3;
  if(invoke(c,start,rows,r,true,nullptr)!=cudaSuccess||cudaDeviceSynchronize()!=cudaSuccess)return 4;
  cudaMemcpy(a.data(),t.out,a.size()*sizeof(float),cudaMemcpyDeviceToHost); cudaMemcpy(b.data(),r.out,b.size()*sizeof(float),cudaMemcpyDeviceToHost); cudaMemcpy(after.data(),t.score,s*sizeof(float),cudaMemcpyDeviceToHost);
  int p1=capture(c,start,1,t,false),p3=capture(c,start,3,t,false),p9=capture(c,start,9,t,false),p64=capture(c,start,64,t,false),r1=capture(c,start,1,r,true),r3=capture(c,start,3,r,true),r9=capture(c,start,9,r,true),r64=capture(c,start,64,r,true); bool scratch=memcmp(before.data(),after.data(),s*sizeof(float))==0; bool finite=true; for(float v:a)finite&=std::isfinite(v); float ma=maxabs(a,b),rr=rms(a,b),co=cosine(a,b); bool rejects=qw38::cuda::launch_attention_prepare_chunk(c,start,0,t.q,t.k,t.v,t.qs,t.ks,t.g,{t.ck,t.cv},{t.tk,t.tv},t.nq,t.nk,t.score,t.out,nullptr)==cudaErrorInvalidValue && qw38::cuda::launch_attention_prepare_chunk(c,c.capacity,1,t.q,t.k,t.v,t.qs,t.ks,t.g,{t.ck,t.cv},{t.tk,t.tv},t.nq,t.nk,t.score,t.out,nullptr)==cudaErrorInvalidValue && qw38::cuda::launch_attention_prepare_chunk(c,start,1,t.q,t.k,t.v,t.qs,t.ks,t.g,{t.ck,t.cv},{t.ck,t.tv},t.nq,t.nk,t.score,t.out,nullptr)==cudaErrorInvalidValue; bool semantic=p1==2&&p3==2&&p9==2&&p64==2&&r1==3&&r3==9&&r9==27&&r64==192&&scratch&&finite&&rejects&&ma<=5e-5f&&rr<=5e-6f&&co>=.999424f;
  printf("{\"type\":\"semantic\",\"production_nodes\":{\"1\":%d,\"3\":%d,\"9\":%d,\"64\":%d},\"reference_nodes\":{\"1\":%d,\"3\":%d,\"9\":%d,\"64\":%d},\"max_abs\":%g,\"rms\":%g,\"cosine\":%g,\"finite\":%s,\"scratch_unchanged\":%s,\"zero_overflow_alias_rejected\":%s,\"status\":\"%s\"}\n",p1,p3,p9,p64,r1,r3,r9,r64,ma,rr,co,finite?"true":"false",scratch?"true":"false",rejects?"true":"false",semantic?"passed":"failed"); release(t); release(r); if(!semantic)return 6;
  for(size_t prefix:{size_t(2048),size_t(8192),size_t(32768)}){rows=64; B x{},y{}; if(!allocate(x,c,rows,prefix)||!allocate(y,c,rows,prefix))return 5; seed(x,c,rows,prefix);seed(y,c,rows,prefix);for(int i=0;i<3;++i)invoke(c,prefix,rows,x,false,nullptr);cudaDeviceSynchronize();cudaEvent_t e0{},e1{};cudaEventCreate(&e0);cudaEventCreate(&e1);std::vector<float>ts(30),rs(3);for(float&v:ts){cudaEventRecord(e0);if(invoke(c,prefix,rows,x,false,nullptr)!=cudaSuccess)return 7;cudaEventRecord(e1);if(cudaEventSynchronize(e1)!=cudaSuccess)return 7;cudaEventElapsedTime(&v,e0,e1);}invoke(c,prefix,rows,y,true,nullptr);cudaDeviceSynchronize();for(float&v:rs){cudaEventRecord(e0);if(invoke(c,prefix,rows,y,true,nullptr)!=cudaSuccess)return 7;cudaEventRecord(e1);cudaEventSynchronize(e1);cudaEventElapsedTime(&v,e0,e1);}double tm=0,rm=0;for(float v:ts)tm+=v;for(float v:rs)rm+=v;tm/=30;rm/=3;bool pass=tm>0&&rm>tm;printf("{\"type\":\"scale\",\"prefix\":%zu,\"tiled_samples\":[",prefix);for(size_t i=0;i<ts.size();++i)printf("%.9g%s",ts[i],i+1==ts.size()?"":",");printf("],\"reference_samples\":[");for(size_t i=0;i<rs.size();++i)printf("%.9g%s",rs[i],i+1==rs.size()?"":",");printf("],\"mean_ms_tiled\":%.9g,\"mean_ms_reference\":%.9g,\"speedup\":%.9g,\"status\":\"%s\"}\n",tm,rm,rm/tm,pass?"passed":"failed");cudaEventDestroy(e0);cudaEventDestroy(e1);release(x);release(y);if(!pass)return 8;} return 0;}
