#include "attention_decode.h"
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <ctime>
#include <string>
#include <vector>

namespace {
using qw38::cuda::AttentionCache;
using qw38::cuda::AttentionConfig;
struct B { float *q{},*k{},*v{},*g{},*qs{},*ks{},*nq{},*nk{},*score{},*out{}; __nv_bfloat16 *ck{},*cv{},*tk{},*tv{}; };
void release(B& b){cudaFree(b.tv);cudaFree(b.tk);cudaFree(b.cv);cudaFree(b.ck);cudaFree(b.out);cudaFree(b.score);cudaFree(b.nk);cudaFree(b.nq);cudaFree(b.ks);cudaFree(b.qs);cudaFree(b.g);cudaFree(b.v);cudaFree(b.k);cudaFree(b.q);}
bool allocate(B& b,const AttentionConfig& c,size_t rows,size_t start){size_t q=qw38::cuda::attention_query_values(c),r=qw38::cuda::attention_kv_row_values(c),cv=qw38::cuda::attention_cache_values(c),s=qw38::cuda::attention_chunk_score_values(c,start,rows);
#define A(x,n) if(cudaMalloc(reinterpret_cast<void**>(&b.x),(n)*sizeof(*b.x))!=cudaSuccess)return false
A(q,rows*q);A(k,rows*r);A(v,rows*r);A(g,rows*q);A(qs,c.head_width);A(ks,c.head_width);A(nq,q);A(nk,r);A(score,s);A(out,rows*q);A(ck,cv);A(cv,cv);A(tk,rows*r);A(tv,rows*r);
#undef A
return true;}
void seed(B& b,const AttentionConfig& c,size_t rows,size_t start){size_t q=qw38::cuda::attention_query_values(c),r=qw38::cuda::attention_kv_row_values(c),cv=qw38::cuda::attention_cache_values(c);std::vector<float> hq(rows*q),hk(rows*r),hv(rows*r),hg(rows*q),s(c.head_width,1.f);for(size_t i=0;i<hq.size();++i){hq[i]=sinf(float(i)*.001f);hg[i]=cosf(float(i)*.002f);}for(size_t i=0;i<hk.size();++i){hk[i]=cosf(float(i)*.003f);hv[i]=sinf(float(i)*.004f);}std::vector<__nv_bfloat16> z(cv);for(size_t i=0;i<cv;++i)z[i]=__float2bfloat16_rn(float(int(i%31)-15)*.015625f);cudaMemcpy(b.q,hq.data(),hq.size()*sizeof(float),cudaMemcpyHostToDevice);cudaMemcpy(b.k,hk.data(),hk.size()*sizeof(float),cudaMemcpyHostToDevice);cudaMemcpy(b.v,hv.data(),hv.size()*sizeof(float),cudaMemcpyHostToDevice);cudaMemcpy(b.g,hg.data(),hg.size()*sizeof(float),cudaMemcpyHostToDevice);cudaMemcpy(b.qs,s.data(),s.size()*sizeof(float),cudaMemcpyHostToDevice);cudaMemcpy(b.ks,s.data(),s.size()*sizeof(float),cudaMemcpyHostToDevice);cudaMemcpy(b.ck,z.data(),z.size()*sizeof(__nv_bfloat16),cudaMemcpyHostToDevice);cudaMemset(b.score,0xA5,qw38::cuda::attention_chunk_score_values(c,start,rows)*sizeof(float));}
cudaError_t invoke(const AttentionConfig& c,size_t start,size_t rows,B& b,bool ref,cudaStream_t stream){AttentionCache committed{b.ck,b.cv},candidate{b.tk,b.tv};return ref?qw38::cuda::launch_attention_prepare_chunk_reference(c,start,rows,b.q,b.k,b.v,b.qs,b.ks,b.g,committed,candidate,b.nq,b.nk,b.score,b.out,stream):qw38::cuda::launch_attention_prepare_chunk(c,start,rows,b.q,b.k,b.v,b.qs,b.ks,b.g,committed,candidate,b.nq,b.nk,b.score,b.out,stream);}
int capture(const AttentionConfig& c,size_t start,size_t rows,B& b,bool ref){cudaStream_t s{};cudaGraph_t g{};cudaGraphExec_t e{};if(cudaStreamCreateWithFlags(&s,cudaStreamNonBlocking)!=cudaSuccess)return -1;if(cudaStreamBeginCapture(s,cudaStreamCaptureModeGlobal)!=cudaSuccess)return -1;cudaError_t x=invoke(c,start,rows,b,ref,s);if(x==cudaSuccess)x=cudaStreamEndCapture(s,&g);if(x!=cudaSuccess){cudaStreamDestroy(s);return -1;}size_t n=0;std::vector<cudaGraphNode_t> nodes;if(x==cudaSuccess)x=cudaGraphGetNodes(g,nullptr,&n);if(x==cudaSuccess){nodes.resize(n);x=cudaGraphGetNodes(g,nodes.data(),&n);}if(x==cudaSuccess)x=cudaGraphInstantiate(&e,g,nullptr,nullptr,0);if(x==cudaSuccess)x=cudaGraphLaunch(e,s);if(x==cudaSuccess)x=cudaStreamSynchronize(s);int k=0;for(auto node:nodes){cudaGraphNodeType t{};if(cudaGraphNodeGetType(node,&t)==cudaSuccess&&t==cudaGraphNodeTypeKernel)++k;}cudaGraphExecDestroy(e);cudaGraphDestroy(g);cudaStreamDestroy(s);return x==cudaSuccess?k:-1;}
float maxabs(const std::vector<float>&a,const std::vector<float>&b){float m=0;for(size_t i=0;i<a.size();++i)m=fmaxf(m,fabsf(a[i]-b[i]));return m;}float rms(const std::vector<float>&a,const std::vector<float>&b){double s=0;for(size_t i=0;i<a.size();++i){double d=a[i]-b[i];s+=d*d;}return sqrtf(float(s/a.size()));}float cosine(const std::vector<float>&a,const std::vector<float>&b){double ab=0,aa=0,bb=0;for(size_t i=0;i<a.size();++i){ab+=a[i]*b[i];aa+=a[i]*a[i];bb+=b[i]*b[i];}return float(ab/sqrt(aa*bb));}
}
int main(){
  AttentionConfig c{24,4,256,64,131072}; size_t rows=9,start=5,q=qw38::cuda::attention_query_values(c),kv=qw38::cuda::attention_kv_row_values(c),cache=qw38::cuda::attention_cache_values(c),s=qw38::cuda::attention_chunk_score_values(c,start,rows); B t{},r{},repeated{},future{},later{},commit_check{};
  if(!allocate(t,c,rows,start)||!allocate(r,c,rows,start)||!allocate(repeated,c,rows,start)||!allocate(future,c,rows,start)||!allocate(later,c,rows,start)||!allocate(commit_check,c,rows,start)) return 2; seed(t,c,rows,start); seed(r,c,rows,start); seed(repeated,c,rows,start); seed(future,c,rows,start); seed(later,c,rows,start);seed(commit_check,c,rows,start);
  std::vector<float>a(rows*q),b(a.size()),before(s),after(s); std::vector<__nv_bfloat16> cache_key_before(cache),cache_value_before(cache),cache_key_after(cache),cache_value_after(cache); cudaMemcpy(before.data(),t.score,s*sizeof(float),cudaMemcpyDeviceToHost);cudaMemcpy(cache_key_before.data(),t.ck,cache*sizeof(cache_key_before[0]),cudaMemcpyDeviceToHost);cudaMemcpy(cache_value_before.data(),t.cv,cache*sizeof(cache_value_before[0]),cudaMemcpyDeviceToHost);
  if(invoke(c,start,rows,t,false,nullptr)!=cudaSuccess||cudaDeviceSynchronize()!=cudaSuccess)return 3;
  if(invoke(c,start,rows,r,true,nullptr)!=cudaSuccess||cudaDeviceSynchronize()!=cudaSuccess)return 4;
  cudaMemcpy(a.data(),t.out,a.size()*sizeof(float),cudaMemcpyDeviceToHost); cudaMemcpy(b.data(),r.out,b.size()*sizeof(float),cudaMemcpyDeviceToHost); cudaMemcpy(after.data(),t.score,s*sizeof(float),cudaMemcpyDeviceToHost);
  bool scratch=memcmp(before.data(),after.data(),s*sizeof(float))==0,finite=true; for(float v:a)finite&=std::isfinite(v); float ma=maxabs(a,b),rr=rms(a,b),co=cosine(a,b);
  std::vector<__nv_bfloat16> tc(rows*kv),tv(rows*kv),rc(rows*kv),rv(rows*kv); cudaMemcpy(tc.data(),t.tk,tc.size()*sizeof(tc[0]),cudaMemcpyDeviceToHost);cudaMemcpy(tv.data(),t.tv,tv.size()*sizeof(tv[0]),cudaMemcpyDeviceToHost);cudaMemcpy(rc.data(),r.tk,rc.size()*sizeof(rc[0]),cudaMemcpyDeviceToHost);cudaMemcpy(rv.data(),r.tv,rv.size()*sizeof(rv[0]),cudaMemcpyDeviceToHost);cudaMemcpy(cache_key_after.data(),t.ck,cache*sizeof(cache_key_after[0]),cudaMemcpyDeviceToHost);cudaMemcpy(cache_value_after.data(),t.cv,cache*sizeof(cache_value_after[0]),cudaMemcpyDeviceToHost);
  bool candidate_exact=memcmp(tc.data(),rc.data(),tc.size()*sizeof(tc[0]))==0&&memcmp(tv.data(),rv.data(),tv.size()*sizeof(tv[0]))==0; bool cache_unchanged=memcmp(cache_key_before.data(),cache_key_after.data(),cache*sizeof(cache_key_before[0]))==0&&memcmp(cache_value_before.data(),cache_value_after.data(),cache*sizeof(cache_value_before[0]))==0;
  bool zero_rejected=invoke(c,start,0,t,false,nullptr)==cudaErrorInvalidValue; bool overflow_rejected=invoke(c,c.capacity,1,t,false,nullptr)==cudaErrorInvalidValue; bool alias_rejected=qw38::cuda::launch_attention_prepare_chunk(c,start,1,t.q,t.k,t.v,t.qs,t.ks,t.g,{t.ck,t.cv},{t.ck,t.tv},t.nq,t.nk,t.score,t.out,nullptr)==cudaErrorInvalidValue;
  float ma3=0,rr3=0,co3=0; if(invoke(c,start,3,t,false,nullptr)!=cudaSuccess||invoke(c,start,3,r,true,nullptr)!=cudaSuccess||cudaDeviceSynchronize()!=cudaSuccess)return 6;std::vector<float>a3(3*q),b3(3*q);cudaMemcpy(a3.data(),t.out,a3.size()*sizeof(float),cudaMemcpyDeviceToHost);cudaMemcpy(b3.data(),r.out,b3.size()*sizeof(float),cudaMemcpyDeviceToHost);ma3=maxabs(a3,b3);rr3=rms(a3,b3);co3=cosine(a3,b3);
  bool normalized_equal=true; if(invoke(c,start,1,t,false,nullptr)!=cudaSuccess||invoke(c,start,1,r,true,nullptr)!=cudaSuccess||cudaDeviceSynchronize()!=cudaSuccess)return 6;std::vector<float>nqt(q),nqr(q),nkt(kv),nkr(kv);cudaMemcpy(nqt.data(),t.nq,q*sizeof(float),cudaMemcpyDeviceToHost);cudaMemcpy(nqr.data(),r.nq,q*sizeof(float),cudaMemcpyDeviceToHost);cudaMemcpy(nkt.data(),t.nk,kv*sizeof(float),cudaMemcpyDeviceToHost);cudaMemcpy(nkr.data(),r.nk,kv*sizeof(float),cudaMemcpyDeviceToHost);normalized_equal=memcmp(nqt.data(),nqr.data(),q*sizeof(float))==0&&memcmp(nkt.data(),nkr.data(),kv*sizeof(float))==0;
  bool last_position=invoke(c,c.capacity-1,1,t,false,nullptr)==cudaSuccess&&cudaDeviceSynchronize()==cudaSuccess;
  std::uint64_t frontier_value=17,*frontier{};cudaMalloc(reinterpret_cast<void**>(&frontier),sizeof(frontier_value));cudaMemcpy(frontier,&frontier_value,sizeof(frontier_value),cudaMemcpyHostToDevice);std::uint64_t frontier_after=0;cudaMemcpy(&frontier_after,frontier,sizeof(frontier_after),cudaMemcpyDeviceToHost);bool frontier_unchanged=frontier_after==frontier_value;
  std::uint64_t repeated_frontier_value=start,*repeated_frontier{};cudaMalloc(reinterpret_cast<void**>(&repeated_frontier),sizeof(repeated_frontier_value));cudaMemcpy(repeated_frontier,&repeated_frontier_value,sizeof(repeated_frontier_value),cudaMemcpyHostToDevice);bool repeated_ok=true;for(size_t i=0;i<rows;++i){AttentionCache committed_cache{repeated.ck,repeated.cv},candidate_cache{repeated.tk+i*kv,repeated.tv+i*kv};repeated_ok&=qw38::cuda::launch_attention_prepare_chunk(c,start+i,1,repeated.q+i*q,repeated.k+i*kv,repeated.v+i*kv,repeated.qs,repeated.ks,repeated.g+i*q,committed_cache,candidate_cache,repeated.nq,repeated.nk,repeated.score,repeated.out+i*q,nullptr)==cudaSuccess;repeated_ok&=cudaDeviceSynchronize()==cudaSuccess;repeated_ok&=qw38::cuda::launch_attention_commit_chunk(c,start+i,1,candidate_cache,committed_cache,start+i+1,repeated_frontier,nullptr)==cudaSuccess;repeated_ok&=cudaDeviceSynchronize()==cudaSuccess;}std::vector<float>repeated_output(rows*q);std::vector<__nv_bfloat16>repeated_key(rows*kv),repeated_value(rows*kv);std::uint64_t repeated_frontier_after=0;cudaMemcpy(repeated_output.data(),repeated.out,repeated_output.size()*sizeof(float),cudaMemcpyDeviceToHost);cudaMemcpy(repeated_key.data(),repeated.ck+start*kv,repeated_key.size()*sizeof(repeated_key[0]),cudaMemcpyDeviceToHost);cudaMemcpy(repeated_value.data(),repeated.cv+start*kv,repeated_value.size()*sizeof(repeated_value[0]),cudaMemcpyDeviceToHost);cudaMemcpy(&repeated_frontier_after,repeated_frontier,sizeof(repeated_frontier_after),cudaMemcpyDeviceToHost);bool chunk_output=repeated_ok&&memcmp(a.data(),repeated_output.data(),a.size()*sizeof(float))==0;bool chunk_candidate=repeated_ok&&memcmp(tc.data(),repeated_key.data(),tc.size()*sizeof(tc[0]))==0&&memcmp(tv.data(),repeated_value.data(),tv.size()*sizeof(tv[0]))==0&&repeated_frontier_after==start+rows;cudaFree(repeated_frontier);
  std::vector<__nv_bfloat16> sentinel_row(kv,__float2bfloat16_rn(123.f));cudaMemcpy(future.ck+(start+rows+1)*kv,sentinel_row.data(),sentinel_row.size()*sizeof(sentinel_row[0]),cudaMemcpyHostToDevice);cudaMemcpy(future.cv+(start+rows+1)*kv,sentinel_row.data(),sentinel_row.size()*sizeof(sentinel_row[0]),cudaMemcpyHostToDevice);bool future_ok=invoke(c,start,rows,future,false,nullptr)==cudaSuccess&&cudaDeviceSynchronize()==cudaSuccess;std::vector<float>future_output(rows*q);cudaMemcpy(future_output.data(),future.out,future_output.size()*sizeof(float),cudaMemcpyDeviceToHost);bool future_excluded=future_ok&&memcmp(a.data(),future_output.data(),a.size()*sizeof(float))==0;
  std::vector<float>later_key(kv,321.f),later_value(kv,-321.f);cudaMemcpy(later.k+(rows-1)*kv,later_key.data(),later_key.size()*sizeof(float),cudaMemcpyHostToDevice);cudaMemcpy(later.v+(rows-1)*kv,later_value.data(),later_value.size()*sizeof(float),cudaMemcpyHostToDevice);bool later_ok=invoke(c,start,rows,later,false,nullptr)==cudaSuccess&&cudaDeviceSynchronize()==cudaSuccess;std::vector<float>later_output(rows*q);cudaMemcpy(later_output.data(),later.out,later_output.size()*sizeof(float),cudaMemcpyDeviceToHost);bool later_excluded=later_ok&&memcmp(a.data(),later_output.data(),(rows-1)*q*sizeof(float))==0;
  bool commit_prepared=invoke(c,start,rows,commit_check,false,nullptr)==cudaSuccess&&cudaDeviceSynchronize()==cudaSuccess;std::vector<__nv_bfloat16>commit_candidate_key(rows*kv),commit_candidate_value(rows*kv);cudaMemcpy(commit_candidate_key.data(),commit_check.tk,commit_candidate_key.size()*sizeof(commit_candidate_key[0]),cudaMemcpyDeviceToHost);cudaMemcpy(commit_candidate_value.data(),commit_check.tv,commit_candidate_value.size()*sizeof(commit_candidate_value[0]),cudaMemcpyDeviceToHost);bool commit_ok=commit_prepared&&qw38::cuda::launch_attention_commit_chunk(c,start,rows,{commit_check.tk,commit_check.tv},{commit_check.ck,commit_check.cv},start+rows,frontier,nullptr)==cudaSuccess&&cudaDeviceSynchronize()==cudaSuccess;cudaMemcpy(&frontier_after,frontier,sizeof(frontier_after),cudaMemcpyDeviceToHost);std::vector<__nv_bfloat16> committed_key(rows*kv),committed_value(rows*kv);cudaMemcpy(committed_key.data(),commit_check.ck+start*kv,committed_key.size()*sizeof(committed_key[0]),cudaMemcpyDeviceToHost);cudaMemcpy(committed_value.data(),commit_check.cv+start*kv,committed_value.size()*sizeof(committed_value[0]),cudaMemcpyDeviceToHost);bool commit_exact=commit_ok&&memcmp(committed_key.data(),commit_candidate_key.data(),committed_key.size()*sizeof(committed_key[0]))==0&&memcmp(committed_value.data(),commit_candidate_value.data(),committed_value.size()*sizeof(committed_value[0]))==0;bool commit_frontier=frontier_after==start+rows;cudaFree(frontier);
  release(t);release(r);release(repeated);release(future);release(later);release(commit_check);
  B graph{};if(!allocate(graph,c,64,start))return 5;seed(graph,c,64,start);int p1=capture(c,start,1,graph,false),p3=capture(c,start,3,graph,false),p9=capture(c,start,9,graph,false),p64=capture(c,start,64,graph,false),r1=capture(c,start,1,graph,true),r3=capture(c,start,3,graph,true),r9=capture(c,start,9,graph,true),r64=capture(c,start,64,graph,true);release(graph);bool graphs=p1==2&&p3==2&&p9==2&&p64==2&&r1==3&&r3==9&&r9==27&&r64==192;
  bool semantic=finite&&candidate_exact&&chunk_output&&chunk_candidate&&cache_unchanged&&frontier_unchanged&&commit_exact&&commit_frontier&&future_excluded&&later_excluded&&scratch&&zero_rejected&&overflow_rejected&&alias_rejected&&last_position&&normalized_equal&&graphs&&ma<=5e-5f&&rr<=5e-6f&&co>=.999424f&&ma3<=5e-5f&&rr3<=5e-6f&&co3>=.999424f;if(!semantic){fprintf(stderr,"semantic failure finite=%d candidate=%d repeated_output=%d repeated_candidate=%d cache=%d frontier=%d commit=%d commit_frontier=%d future=%d later=%d scratch=%d zero=%d overflow=%d alias=%d last=%d normalized=%d graphs=%d metrics9=%d metrics3=%d\n",finite,candidate_exact,chunk_output,chunk_candidate,cache_unchanged,frontier_unchanged,commit_exact,commit_frontier,future_excluded,later_excluded,scratch,zero_rejected,overflow_rejected,alias_rejected,last_position,normalized_equal,graphs,ma<=5e-5f&&rr<=5e-6f&&co>=.999424f,ma3<=5e-5f&&rr3<=5e-6f&&co3>=.999424f);return 6;}
  struct Scale{size_t prefix;std::vector<float>tiled,reference;double tm,rm;};std::vector<Scale> scales;
  for(size_t prefix:{size_t(2048),size_t(8192),size_t(32768)}){rows=64;B x{},y{};if(!allocate(x,c,rows,prefix)||!allocate(y,c,rows,prefix))return 5;seed(x,c,rows,prefix);seed(y,c,rows,prefix);for(int i=0;i<3;++i)invoke(c,prefix,rows,x,false,nullptr);cudaDeviceSynchronize();cudaEvent_t e0{},e1{};cudaEventCreate(&e0);cudaEventCreate(&e1);Scale z{prefix,std::vector<float>(30),std::vector<float>(3),0,0};for(float&v:z.tiled){cudaEventRecord(e0);if(invoke(c,prefix,rows,x,false,nullptr)!=cudaSuccess)return 7;cudaEventRecord(e1);if(cudaEventSynchronize(e1)!=cudaSuccess)return 7;cudaEventElapsedTime(&v,e0,e1);}invoke(c,prefix,rows,y,true,nullptr);cudaDeviceSynchronize();for(float&v:z.reference){cudaEventRecord(e0);if(invoke(c,prefix,rows,y,true,nullptr)!=cudaSuccess)return 7;cudaEventRecord(e1);if(cudaEventSynchronize(e1)!=cudaSuccess)return 7;cudaEventElapsedTime(&v,e0,e1);}for(float v:z.tiled)z.tm+=v;for(float v:z.reference)z.rm+=v;z.tm/=30;z.rm/=3;cudaEventDestroy(e0);cudaEventDestroy(e1);release(x);release(y);if(!(z.tm>0&&z.rm>z.tm))return 8;scales.push_back(z);}
  cudaDeviceProp prop{};int dev=0,driver=0,runtime=0;cudaGetDevice(&dev);cudaGetDeviceProperties(&prop,dev);cudaDriverGetVersion(&driver);cudaRuntimeGetVersion(&runtime);std::time_t now=std::time(nullptr);char utc[32]{};std::tm tm{};gmtime_r(&now,&tm);std::strftime(utc,sizeof(utc),"%Y-%m-%dT%H:%M:%SZ",&tm);
  printf("QW38_TILED_ATTENTION_RESULT={\"schema_version\":2,\"task\":\"OPT-005\",\"status\":\"measured\",\"device\":\"%s\",\"compute_capability\":\"%d.%d\",\"driver\":\"%d.%d\",\"runtime\":\"%d.%d\",\"toolkit\":\"CUDA 13.0.2\",\"pinned_image\":\"qw38-cuda:13.0.2\",\"measurement_utc\":\"%s\",\"warmups\":{\"tiled\":3,\"reference\":1},\"proof_limits\":{\"bf16_max_abs\":0.00005,\"bf16_rms\":0.000005,\"oracle_max_abs\":0.051,\"oracle_rms\":0.0016,\"oracle_cosine\":0.999424},\"semantic\":{\"predicates\":{",prop.name,prop.major,prop.minor,driver/1000,(driver%1000)/10,runtime/1000,(runtime%1000)/10,utc);
  const char* names[]={"finite_output","candidate_bf16_exact","chunk_repeated_output_exact","chunk_repeated_candidate_exact","prepare_cache_unchanged","prepare_frontier_unchanged","commit_cache_exact","commit_frontier_exact","future_committed_excluded","later_candidate_excluded","scratch_unchanged","zero_count_rejected","capacity_overflow_rejected","candidate_alias_rejected","last_position_executed","normalized_qk_one_row_equal","graphs_executed"};for(int i=0;i<17;++i)printf("\"%s\":true%s",names[i],i==16?"":",");printf("},\"metrics\":{\"3\":{\"max_abs\":%.9g,\"rms\":%.9g,\"cosine\":%.9g},\"9\":{\"max_abs\":%.9g,\"rms\":%.9g,\"cosine\":%.9g}},\"production_kernel_nodes\":{\"1\":%d,\"3\":%d,\"9\":%d,\"64\":%d},\"reference_kernel_nodes\":{\"1\":%d,\"3\":%d,\"9\":%d,\"64\":%d}},\"scaling\":[",ma3,rr3,co3,ma,rr,co,p1,p3,p9,p64,r1,r3,r9,r64);
  for(size_t j=0;j<scales.size();++j){const auto&z=scales[j];printf("{\"prefix\":%zu,\"rows\":64,\"tiled_samples\":[",z.prefix);for(size_t i=0;i<z.tiled.size();++i)printf("%.9g%s",z.tiled[i],i+1==z.tiled.size()?"":",");printf("],\"reference_samples\":[");for(size_t i=0;i<z.reference.size();++i)printf("%.9g%s",z.reference[i],i+1==z.reference.size()?"":",");printf("],\"mean_ms_tiled\":%.9g,\"mean_ms_reference\":%.9g,\"speedup\":%.9g}%s",z.tm,z.rm,z.rm/z.tm,j+1==scales.size()?"":",");}
  printf("],\"claim\":\"component-only production-shape tiled attention timing; excludes projections, scheduler, and end-to-end recovery\"}\n");return 0;}
